import React, {Fragment} from 'react'

export const About = () => (
    <Fragment>
        <h1>about</h1>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quam, laborum? Obcaecati alias eaque est in autem voluptate maxime explicabo aspernatur quaerat delectus vel, nulla culpa esse commodi corporis, excepturi saepe. Eos ab obcaecati eveniet est esse consequuntur sunt magnam. Id itaque qui architecto, maxime ullam cupiditate eum voluptatem non aperiam cum aliquam, similique quaerat nihil eaque recusandae tempora ratione nostrum suscipit earum odit, debitis voluptate facere assumenda! Dignissimos aperiam exercitationem saepe, ipsa aspernatur iste eaque quis excepturi ea illo, distinctio obcaecati ab aliquid dolores illum mollitia natus assumenda esse totam enim repellat, quas laboriosam perferendis? Cupiditate reprehenderit iure reiciendis impedit eos temporibus, assumenda, facilis accusamus quisquam vel culpa repudiandae? Iusto unde similique eaque ab ullam quasi nisi? Quae, sint pariatur eveniet blanditiis iste suscipit vel quos. Modi minima recusandae autem id, expedita dicta nulla sit dolore beatae consequatur, placeat accusamus ab magnam, nobis iure. Eveniet asperiores autem sequi quia delectus corporis temporibus, commodi sint doloribus earum aliquam, voluptatum eos modi molestias beatae aliquid obcaecati sed necessitatibus fugit libero vel repellat fugiat. Rem ex rerum facere voluptate itaque dolorum nesciunt tempore doloremque, voluptatum veritatis deleniti sequi neque modi quisquam obcaecati doloribus error optio, atque at minus cupiditate! Porro laboriosam obcaecati ducimus dolores nisi delectus natus modi iste velit, non magnam tenetur fugiat dolorum provident laudantium explicabo vel voluptatum quidem nesciunt mollitia, iure cupiditate libero consequatur repellendus! Nulla a saepe aperiam. Voluptas ducimus iure esse beatae atque reiciendis neque temporibus obcaecati error, non totam ipsum distinctio eaque dolore repellat aperiam aliquam soluta unde? Sit necessitatibus velit vel suscipit ratione voluptates possimus cupiditate asperiores? Velit officiis, corporis saepe asperiores tempora praesentium fuga fugiat ut! Deleniti nihil, ullam, quis laboriosam officiis ea assumenda libero quae illum, tempore maxime dolorum? Distinctio necessitatibus reprehenderit laborum repellat nesciunt architecto nostrum voluptas cupiditate unde, tenetur, veritatis porro! Fuga.</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptates alias earum non, voluptatibus sit atque voluptatum mollitia quod expedita asperiores accusantium. Aut recusandae possimus accusantium! Doloribus sint labore voluptatum aspernatur deleniti eos culpa accusamus iure velit accusantium natus minus possimus omnis, sunt quos, veritatis rem quis! Iusto iste quisquam eius dolorum molestiae perspiciatis amet facere, placeat totam corporis ipsam quidem vero recusandae iure eos vitae illo excepturi error enim delectus perferendis labore architecto doloremque atque? Laborum eligendi, aspernatur corrupti atque laboriosam aliquam a, quibusdam reprehenderit repellat officiis dolorum, ullam vero. Voluptate, corrupti quam non tempore officia numquam quod exercitationem id!</p>
    </Fragment>
)
